# Generated by Django 5.2.1 on 2026-04-22 19:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(help_text='Used as the tenant subdomain. Lowercase, alphanumerics and hyphens.', max_length=63, unique=True, validators=[django.core.validators.RegexValidator(message='Slug must be lowercase alphanumerics with optional hyphens, not starting or ending with a hyphen.', regex='^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$')], verbose_name='slug')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=16, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['status', 'slug'], name='org_status_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('INACTIVE', 'Inactive'), ('EXPIRED', 'Expired')], db_index=True, default='INVITED', max_length=16, verbose_name='status')),
                ('invited_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('deactivated_at', models.DateTimeField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Post-login landing org for this user when none is selected.', verbose_name='default membership')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'membership',
                'verbose_name_plural': 'memberships',
                'ordering': ['organization__name', 'user__email'],
                'indexes': [models.Index(fields=['user', 'status'], name='membership_user_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='membership_user_org_unique'), models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='membership_single_default_per_user')],
            },
        ),
    ]
