# Generated by Django 5.1.15 on 2026-04-29 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("RESALE", "Resale"),
                            ("MANUFACTURED", "Manufactured"),
                        ],
                        help_text="RESALE products are purchased externally and resold. MANUFACTURED products are built in-house from a BOM.",
                        max_length=20,
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        help_text="Stock keeping unit — unique within an organization.",
                        max_length=64,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft-disable flag. Inactive products are hidden from the quote-line picker but retained for historical references.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ("name",),
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active", "name"],
                        name="prod_product_org_active_idx",
                    ),
                    models.Index(
                        fields=["organization", "product_type", "is_active"],
                        name="prod_product_org_type_act_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "sku"), name="prod_product_uniq_org_sku"
                    )
                ],
            },
        ),
    ]
