# Generated by Django 5.2.1 on 2026-04-23 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text="Capability code, e.g. 'leads.view'. Follows {domain}.{resource}.{action}.", max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('domain', models.CharField(db_index=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'capability',
                'verbose_name_plural': 'capabilities',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False, help_text='True for platform-seeded default roles. Read-only to tenants.')),
                ('system_key', models.CharField(blank=True, choices=[('OWNER', 'Owner'), ('ORG_ADMIN', 'Org Admin'), ('REGIONAL_MANAGER', 'Regional Manager'), ('MARKET_MANAGER', 'Market Manager'), ('LOCATION_MANAGER', 'Location Manager'), ('SALES_STAFF', 'Sales Staff'), ('SERVICE_STAFF', 'Service Staff'), ('PRODUCTION_STAFF', 'Production Staff'), ('VIEWER', 'Viewer')], help_text='Identifies the default-role template. Null on tenant-custom roles.', max_length=32, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'ordering': ['organization__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoleCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='rbac.capability')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_capabilities', to='rbac.role')),
            ],
            options={
                'verbose_name': 'role capability',
                'verbose_name_plural': 'role capabilities',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='capabilities',
            field=models.ManyToManyField(related_name='roles', through='rbac.RoleCapability', to='rbac.capability'),
        ),
        migrations.CreateModel(
            name='MembershipCapabilityGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant_type', models.CharField(choices=[('GRANT', 'Grant'), ('DENY', 'Deny')], help_text='GRANT adds the capability; DENY removes it (overrides role grants).', max_length=8)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_grants', to='rbac.capability')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_grants', to='organizations.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'capability grant',
                'verbose_name_plural': 'capability grants',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['membership', 'grant_type'], name='mbr_grant_type_idx')],
                'constraints': [models.UniqueConstraint(fields=('membership', 'capability', 'grant_type'), name='membership_capability_grant_unique')],
            },
        ),
        migrations.AddIndex(
            model_name='rolecapability',
            index=models.Index(fields=['role', 'capability'], name='role_capability_lookup_idx'),
        ),
        migrations.AddConstraint(
            model_name='rolecapability',
            constraint=models.UniqueConstraint(fields=('role', 'capability'), name='role_capability_unique'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='role_org_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('system_key__isnull', False)), fields=('organization', 'system_key'), name='role_org_system_key_unique'),
        ),
    ]
