"""Add MembershipRole through-table for membership-to-role assignments.

The evaluator needs this link to walk membership → roles → capabilities
per spec §10.2 step 4. Hand-written rather than autogenerated to keep
the M2 step 3 ship commit self-contained — autogen is fine but adds a
chicken-egg run (you'd need to do it locally before applying this code).
"""

from __future__ import annotations

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("rbac", "0002_seed_capabilities"),
    ]

    operations = [
        migrations.CreateModel(
            name="MembershipRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to="organizations.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="membership_assignments",
                        to="rbac.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "membership role assignment",
                "verbose_name_plural": "membership role assignments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="membershiprole",
            constraint=models.UniqueConstraint(
                fields=("membership", "role"),
                name="membership_role_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="membershiprole",
            index=models.Index(
                fields=["membership"],
                name="mbr_role_membership_idx",
            ),
        ),
    ]
