# Generated by Django 5.1.15 on 2026-04-29 19:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog_materials", "0001_initial"),
        ("catalog_products", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Display name of the supplier; unique within an organization.",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("INACTIVE", "Inactive"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("website", models.URLField(blank=True, default="")),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "supplier",
                "verbose_name_plural": "suppliers",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="SupplierProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "supplier_sku",
                    models.CharField(
                        help_text="The supplier's own SKU/code for this item.",
                        max_length=64,
                    ),
                ),
                (
                    "default_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Per-unit cost from this supplier. Base input to the resale pricing strategy. Zero allowed (unpriced placeholder); negative is rejected.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Typical lead time in days from order to delivery. NULL when unknown. Single field rather than min/max — if the project ever needs a range, that's an additive change.",
                        null=True,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_offerings",
                        to="catalog_products.product",
                    ),
                ),
                (
                    "raw_material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_offerings",
                        to="catalog_materials.rawmaterial",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_products",
                        to="catalog_suppliers.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "supplier product",
                "verbose_name_plural": "supplier products",
                "ordering": ("supplier__name", "supplier_sku"),
            },
        ),
        migrations.AddIndex(
            model_name="supplier",
            index=models.Index(
                fields=["organization", "status", "name"],
                name="sup_supplier_org_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="sup_supplier_uniq_org_name"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(
                fields=["organization", "supplier"], name="sup_sp_org_supplier_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(
                fields=["organization", "product"], name="sup_sp_org_product_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supplierproduct",
            index=models.Index(
                fields=["organization", "raw_material"], name="sup_sp_org_material_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("product__isnull", False), ("raw_material__isnull", True)
                    ),
                    models.Q(
                        ("product__isnull", True), ("raw_material__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="sup_sp_target_xor",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierproduct",
            constraint=models.UniqueConstraint(
                condition=models.Q(("product__isnull", False)),
                fields=("supplier", "product"),
                name="sup_sp_uniq_supplier_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierproduct",
            constraint=models.UniqueConstraint(
                condition=models.Q(("raw_material__isnull", False)),
                fields=("supplier", "raw_material"),
                name="sup_sp_uniq_supplier_material",
            ),
        ),
    ]
