# Generated by Django 5.1.15 on 2026-04-30 13:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog_products", "0001_initial"),
        ("catalog_services", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[("MARKUP_PERCENT", "Markup percent over cost")],
                        help_text="Which pricing formula this rule represents. Drives how `parameters` is interpreted.",
                        max_length=32,
                    ),
                ),
                (
                    "target_line_type",
                    models.CharField(
                        choices=[
                            ("SERVICE", "Service"),
                            ("RESALE", "Resale Product"),
                            ("MANUFACTURED", "Manufactured Product"),
                        ],
                        help_text="Which line type this rule applies to.",
                        max_length=20,
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        default=dict,
                        help_text='Rule-type-specific parameters. For MARKUP_PERCENT: {"markup_percent": "0.25"} — Decimal as string. Validated in clean() against the rule_type.',
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft-disable flag. Inactive rules are skipped by the resolution algorithm but retained for audit.",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Higher number wins when multiple rules match at the same specificity level. Default 0.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "target_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this rule applies only to this specific product. Mutually exclusive with target_service.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pricing_rules",
                        to="catalog_products.product",
                    ),
                ),
                (
                    "target_service",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, this rule applies only to this specific service. Mutually exclusive with target_product.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pricing_rules",
                        to="catalog_services.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "pricing rule",
                "verbose_name_plural": "pricing rules",
                "ordering": ("target_line_type", "-priority", "-created_at"),
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active", "target_line_type"],
                        name="pricing_rule_resolution_idx",
                    ),
                    models.Index(
                        fields=["organization", "target_service"],
                        name="pricing_rule_org_svc_idx",
                    ),
                    models.Index(
                        fields=["organization", "target_product"],
                        name="pricing_rule_org_prod_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("target_product__isnull", True),
                                ("target_service__isnull", True),
                            ),
                            models.Q(
                                ("target_product__isnull", True),
                                ("target_service__isnull", False),
                            ),
                            models.Q(
                                ("target_product__isnull", False),
                                ("target_service__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="pricing_rule_target_at_most_one",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("target_line_type", "SERVICE"),
                                ("target_product__isnull", True),
                            ),
                            models.Q(
                                ("target_line_type__in", ["RESALE", "MANUFACTURED"]),
                                ("target_service__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="pricing_rule_target_coherent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PricingSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quote_line_id",
                    models.BigIntegerField(
                        help_text="ID of the quote line this snapshot prices. Plain integer for now; converts to a FK when QuoteLine model lands."
                    ),
                ),
                (
                    "line_type",
                    models.CharField(
                        choices=[
                            ("SERVICE", "Service"),
                            ("RESALE", "Resale Product"),
                            ("MANUFACTURED", "Manufactured Product"),
                        ],
                        help_text="Line type at the time of pricing — SERVICE/RESALE/MANUFACTURED.",
                        max_length=20,
                    ),
                ),
                (
                    "base_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Pre-markup, pre-discount cost basis.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "markup_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Money added by markup. Zero is allowed; negative is not.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Money taken off as discount (before any user override). Stored as a positive value; subtracted in the math.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "unit_price_final",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The unit price actually quoted, after override if any.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "override_applied",
                    models.BooleanField(
                        default=False,
                        help_text="True if a user override changed the engine-computed price.",
                    ),
                ),
                (
                    "override_unit_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The override value, if any. NULL when override_applied=False.",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "override_reason",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Required (non-empty) if override_applied=True; ignored otherwise. Enforced in clean().",
                    ),
                ),
                (
                    "inputs",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Full input bundle: catalog item id, supplier_product id (resale), BOM id (manufactured), labor estimate (manufactured), applied PricingRule id, etc. Schema is documented per line type by the strategy engine.",
                    ),
                ),
                (
                    "breakdown",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Line-type-specific cost breakdown beyond the universal fields above — e.g. material_cost vs labor_cost split for manufactured products.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="True for the current snapshot of this quote_line. Flipped to False when a new snapshot supersedes this one. Never deleted.",
                    ),
                ),
                (
                    "engine_version",
                    models.CharField(
                        default="1.0",
                        help_text="Pricing engine version that produced this snapshot. Bumped on engine math changes; old snapshots retain their original version for reproducibility.",
                        max_length=16,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "pricing snapshot",
                "verbose_name_plural": "pricing snapshots",
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["organization", "quote_line_id", "-created_at"],
                        name="pricing_snap_org_qline_idx",
                    ),
                    models.Index(
                        fields=["organization", "line_type", "is_active"],
                        name="pricing_snap_org_type_act_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("organization", "quote_line_id"),
                        name="pricing_snap_uniq_active_qline",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("override_applied", False),
                                ("override_unit_price__isnull", True),
                            ),
                            models.Q(
                                ("override_applied", True),
                                ("override_unit_price__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="pricing_snap_override_coherent",
                    ),
                ],
            },
        ),
    ]
