# Generated by Django 5.1.15 on 2026-04-29 23:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog_materials", "0001_initial"),
        ("catalog_products", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BOM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "version",
                    models.CharField(
                        help_text="Free-text version label (e.g. 'v2.1', '2025-Q1-rev2'). Unique per (organization, finished_product) so two BOMs for the same product can't share a version string.",
                        max_length=64,
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(
                        help_text="Date this BOM is intended to take effect. DRAFT BOMs may have a future date; ACTIVE/SUPERSEDED BOMs typically have a past or current date. Workflow validation lives in clean()."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "finished_product",
                    models.ForeignKey(
                        help_text="The Product this BOM produces. Should be a MANUFACTURED-type product; this is enforced at the service layer, not the DB.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boms",
                        to="catalog_products.product",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM",
                "verbose_name_plural": "BOMs",
                "ordering": ("finished_product", "-effective_from", "-version"),
            },
        ),
        migrations.CreateModel(
            name="BOMLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Display quantity in `unit_of_measure`. Documents what to physically use. NOT used in pricing math — see `cost_basis_quantity` for that.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("EACH", "Each"),
                            ("KG", "Kilogram"),
                            ("G", "Gram"),
                            ("LB", "Pound"),
                            ("OZ", "Ounce"),
                            ("L", "Liter"),
                            ("ML", "Milliliter"),
                            ("GAL", "Gallon"),
                            ("FL_OZ", "Fluid Ounce"),
                            ("M", "Meter"),
                            ("FT", "Foot"),
                            ("M2", "Square Meter"),
                            ("FT2", "Square Foot"),
                            ("M3", "Cubic Meter"),
                            ("FT3", "Cubic Foot"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Display unit. Need not match the RawMaterial's catalog UoM.",
                        max_length=10,
                    ),
                ),
                (
                    "cost_basis_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Same physical amount as `quantity`, but expressed in the RawMaterial's catalog UoM. THIS is the field pricing math uses. User does the conversion at entry time.",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "cost_reference",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Per-RawMaterial-catalog-unit cost reference. Tracks RawMaterial.current_cost while the BOM is DRAFT; frozen on ACTIVE transition. Service-layer responsibility.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "bom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="catalog_manufacturing.bom",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "raw_material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bom_lines",
                        to="catalog_materials.rawmaterial",
                    ),
                ),
            ],
            options={
                "verbose_name": "BOM line",
                "verbose_name_plural": "BOM lines",
                "ordering": ("bom", "raw_material__name"),
            },
        ),
        migrations.AddIndex(
            model_name="bom",
            index=models.Index(
                fields=["organization", "finished_product", "status"],
                name="bom_org_product_status_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="bom",
            constraint=models.UniqueConstraint(
                fields=("organization", "finished_product", "version"),
                name="bom_uniq_org_product_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="bom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("organization", "finished_product"),
                name="bom_uniq_active_per_product",
            ),
        ),
        migrations.AddIndex(
            model_name="bomline",
            index=models.Index(
                fields=["organization", "bom"], name="bom_line_org_bom_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="bomline",
            constraint=models.UniqueConstraint(
                fields=("bom", "raw_material"), name="bom_line_uniq_bom_material"
            ),
        ),
    ]
