# Generated by Django 5.1.15 on 2026-04-29 18:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short stable identifier, unique within an organization.",
                        max_length=64,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft-disable flag. Inactive categories are hidden from the quote-line picker but retained for historical references.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "service category",
                "verbose_name_plural": "service categories",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Service code, unique within an organization.",
                        max_length=64,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "catalog_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Flat unit price used as the v1 base for service line pricing.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft-disable flag. Inactive services are hidden from the quote-line picker but retained for historical references.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="A category cannot be deleted while services reference it.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="services",
                        to="catalog_services.servicecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "service",
                "verbose_name_plural": "services",
                "ordering": ("name",),
            },
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(
                fields=["organization", "is_active", "name"],
                name="svc_svccat_org_active_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="servicecategory",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="svc_svccat_uniq_org_code"
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["organization", "is_active", "name"],
                name="svc_service_org_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="service",
            index=models.Index(
                fields=["organization", "category", "is_active"],
                name="svc_service_org_cat_act_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="service",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="svc_service_uniq_org_code"
            ),
        ),
    ]
