# Generated by Django 5.1.15 on 2026-04-29 19:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RawMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sku",
                    models.CharField(
                        help_text="Stock keeping unit — unique within an organization.",
                        max_length=64,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("EACH", "Each"),
                            ("KG", "Kilogram"),
                            ("G", "Gram"),
                            ("LB", "Pound"),
                            ("OZ", "Ounce"),
                            ("L", "Liter"),
                            ("ML", "Milliliter"),
                            ("GAL", "Gallon"),
                            ("FL_OZ", "Fluid Ounce"),
                            ("M", "Meter"),
                            ("FT", "Foot"),
                            ("M2", "Square Meter"),
                            ("FT2", "Square Foot"),
                            ("M3", "Cubic Meter"),
                            ("FT3", "Cubic Foot"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Unit pricing math is in. Cost values for this material are interpreted as cost-per-unit-of-measure. Mismatched units are a real data-quality risk; choose deliberately.",
                        max_length=10,
                    ),
                ),
                (
                    "current_cost",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Latest known per-unit cost. Updated when a supplier price change is recorded. Historical snapshots preserve the value at quote time.",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Soft-disable flag. Inactive materials are hidden from the BOM picker but retained for historical references.",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "raw material",
                "verbose_name_plural": "raw materials",
                "ordering": ("name",),
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active", "name"],
                        name="mat_rawmaterial_org_act_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "sku"),
                        name="mat_rawmaterial_uniq_org_sku",
                    )
                ],
            },
        ),
    ]
